--Q1. What is the total revenue generated by male vs. female? What is their percentage contribution? 
SELECT gender, SUM(purchase_amount) AS revenue,
ROUND 
	(SUM(purchase_amount)*100/SUM(SUM(purchase_amount)) OVER(),2) AS pct_contribution
FROM customer
GROUP BY 1;

--Q2. Which customer used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) as average_purchase_amount
FROM customer)
ORDER BY 1;

--Q3. Which are top products with the highest average review rating? 
SELECT item_purchased AS products, 
ROUND(AVG(review_rating)::NUMERIC,2) AS average_review
FROM customer
GROUP BY 1
ORDER BY average_review DESC
LIMIT 5;

--Q3. Compare the average purchase amounts between standard and express shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as avg_purchase_amount,
ROUND
	(AVG(purchase_amount)*100/AVG(AVG(purchase_amount)) OVER()
	,2) AS pct_contribution
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY 1;

-- Q4. Do subscribed customers spend more? Compare average spend and total revenue between 
-- subscribers and non subscribers 
SELECT subscription_status, COUNT(customer_id) AS total_customers,
ROUND (AVG(purchase_amount),2) AS average_spend, 
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Which 5 products have the highest percenrage of purchases with discounts applied? 
SELECT item_purchased AS products,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY 1
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning and Loyal based on their total number of 
-- previous purchases, and show the count of each segment.

WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS total_customers
FROM customer_type
GROUP BY 1
ORDER BY total_customers DESC;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS(
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
DENSE_RANK() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rnk
FROM customer
GROUP BY 1,2
ORDER BY 1,2 
)
SELECT category, item_purchased, total_orders, rnk
FROM item_counts
WHERE rnk<=3
ORDER BY 1,2,3 DESC 

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subsribe? 

SELECT subscription_status,count(*) as total_customers
from customer
where previous_purchases>5
group by 1

-- Q10. What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS total_purchase,
ROUND(
	SUM(purchase_amount)*100/SUM(SUM(purchase_amount)) OVER(),2) AS pct_contribution
FROM customer
GROUP BY 1
ORDER BY pct_contribution DESC

